<?php


namespace app\apiv1\controller;

use think\Controller;
use think\Request;
use controller\BasicIndex;
use think\Db;

class Base extends BasicIndex
{

    protected $wx_user;  //
    public $page;
    public  $max_page_num;
    protected $mini_user;
    protected $wx_user_id;

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stubc
        $page = input('param.page');
        $max_page_num = input('param.max_page_num');
        $this->page = isset($page) ? $page : 1;
        $this->max_page_num = isset($max_page_num) ? $max_page_num : 8;
        $orderBy = input('param.orderBy');
        $this->orderBy = !isset($orderBy) ? 'asc' : $orderBy;
        $token = request()->header('token');
        //$token = '1zBzj8LRXYyGkZGXENNBRGesM8w';
        if (empty($token)) return $this->error('token不能为空','',999);
        //查询的是商城会员信息
        $this->wx_user = Db::table('store_member')->where(['wx_token' => $token])->find();
        $this->wx_user_id = $this->wx_user['id'];
        if ($this->wx_user['is_disable'] == -1)  return $this->error('用户冻结中','',999);
        if (empty($this->wx_user_id))  return $this->error('用户信息不存在','',999);


       
    }


}
