<?php

namespace app\miniapp\controller;

use think\Controller;
use think\Request;
use controller\BasicApi;
use think\Db;

class Base extends BasicApi
{

    protected $wx_user;
    public $page;
    public $max_page_num;
    protected $mini_user;
    protected $wx_user_id;

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $page = input('param.page');
        $max_page_num = input('param.max_page_num');
        $this->page = isset($page) ? $page : 1;
        $this->max_page_num = isset($max_page_num) ? $max_page_num : 8;
        $orderBy = input('param.orderBy');
        $this->orderBy = !isset($orderBy) ? 'asc' : $orderBy;
        $token = request()->header('token');
        if (empty($token)) return $this->error('token不能为空');
        $this->wx_user = Db::table('store_member')->where(['wx_token' => $token])->find();
        $this->wx_user_id = $this->wx_user['id'];
        if (empty($this->wx_user_id))  return $this->error('用户信息不存在');
    }


}
